name: Artifactory Milestone Release

on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: "Milestone release version"
        required: true

jobs:
  build:
    name: Release milestone to Artifactory
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Capture release version
        run: echo RELEASE_VERSION=${{ github.event.inputs.releaseVersion }} >> $GITHUB_ENV

      - name: Update release version
        run: |
          ./mvnw versions:set -DgenerateBackupPoms=false -DnewVersion=$RELEASE_VERSION
          ./mvnw versions:set -DgenerateBackupPoms=false -DnewVersion=$RELEASE_VERSION -pl spring-ai-bom

      - name: Enforce release rules
        run: ./wmvn org.apache.maven.plugins:maven-enforcer-plugin:enforce -Drules=requireReleaseDeps

      - name: Build with Maven and deploy to Artifactory's milestone repository
        env:
          ARTIFACTORY_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
          ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
        run: ./mvnw -P artifactory-milestone -s settings.xml --batch-mode -Dmaven.test.skip=true deploy
